estimator:
  pickle: model.pickl

strategy:
  name: gp
  params:
    seeds: 5
#    kernels:
#      - { name : GPy.kern.Matern32, params : {ARD : True}, option s: {independent : False}}
#    acquisition: { name : ucb, params : {kappa : 2}}

search_space:
  learning_rate_init:
    min: 0.0001
    max: 0.0005
    type: float

  alpha:
    min: 0.00001
    max: 0.001
    type: float

  n_units:
    min: 30
    max: 80
    type: int

  batch_size:
    min: 50
    max: 500
    num: 10
    type: jump
    var_type: int


cv: 3

dataset_loader:
  name: dsv
  params:
    filenames: /home/robert/dataSilvia/data_dpccm.csv
    usecols: 0,1,2,3,4,5,6
    y_col: 7

trials:
    uri: sqlite:///osprey-trials.db


